# Generated by Django 2.0.13 on 2019-03-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20190307_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweetmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='dbid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
