# Generated by Django 2.0.13 on 2019-03-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20190308_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetmodel',
            old_name='dbid',
            new_name='id',
        ),
    ]
