version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    build:
      context: .
      dockerfile: ./dockerfile
    
    depends_on:
      - postgres

    restart: always
    volumes:
    - .:/home/microtwitter
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  postgres:
    container_name: postgres
    restart: always
    image: postgres:9.6
    volumes:
    - /var/lib/postgresql/data
    ports:
      - 5432:5432